### ISSUE TITLE
Non-deterministic behaviour in CI suites

### ISSUE THREAD

**Issue by gsaslis** [3scale/porta#22]
We have some pretty common occurrences of test failures in our pipeline, like the below: 

```
Error Message
failed Signup with Auth0
Stacktrace
    Scenario: Signup with Auth0

And I go to the login page

Message:

    Net::ReadTimeout (Net::ReadTimeout)
/usr/lib/ruby/2.3.0/net/protocol.rb:158:in `rbuf_fill'
/usr/lib/ruby/2.3.0/net/protocol.rb:136:in `readuntil'
/usr/lib/ruby/2.3.0/net/protocol.rb:146:in `readline'
/usr/lib/ruby/2.3.0/net/http/response.rb:40:in `read_status_line'
/usr/lib/ruby/2.3.0/net/http/response.rb:29:in `read_new'
/usr/lib/ruby/2.3.0/net/http.rb:1437:in `block in transport_request'
/usr/lib/ruby/2.3.0/net/http.rb:1434:in `catch'
/usr/lib/ruby/2.3.0/net/http.rb:1434:in `transport_request'
/usr/lib/ruby/2.3.0/net/http.rb:1407:in `request'
/opt/system/vendor/bundle/ruby/2.3.0/bundler/gems/fakeweb-6c9392c03879/lib/fake_web/ext/net_http.rb:53:in `block in request_with_fakeweb'
/opt/system/vendor/bundle/ruby/2.3.0/gems/webmock-1.24.6/lib/webmock/http_lib_adapters/net_http.rb:123:in `start_without_connect'
/opt/system/vendor/bundle/ruby/2.3.0/gems/webmock-1.24.6/lib/webmock/http_lib_adapters/net_http.rb:150:in `start'
/opt/system/vendor/bundle/ruby/2.3.0/bundler/gems/fakeweb-6c9392c03879/lib/fake_web/ext/net_http.rb:51:in `request_with_fakeweb'
/opt/system/vendor/bundle/ruby/2.3.0/gems/webmock-1.24.6/lib/webmock/http_lib_adapters/net_http.rb:97:in `block in request'
/opt/system/vendor/bundle/ruby/2.3.0/gems/webmock-1.24.6/lib/webmock/http_lib_adapters/net_http.rb:110:in `block in request'
/usr/lib/ruby/2.3.0/net/http.rb:853:in `start'
/opt/system/vendor/bundle/ruby/2.3.0/gems/webmock-1.24.6/lib/webmock/http_lib_adapters/net_http.rb:109:in `request'
/opt/system/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/http/default.rb:124:in `response_for'
/opt/system/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/http/default.rb:78:in `request'
/opt/system/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/http/common.rb:61:in `call'
/opt/system/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/w3c_bridge.rb:640:in `execute'
/opt/system/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/w3c_bridge.rb:114:in `create_session'
/opt/system/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/w3c_bridge.rb:76:in `initialize'
/opt/system/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/firefox/w3c_bridge.rb:45:in `initialize'
/opt/system/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/common/driver.rb:52:in `new'
/opt/system/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/common/driver.rb:52:in `for'
/opt/system/vendor/bundle/ruby/2.3.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver.rb:88:in `for'
/opt/system/vendor/bundle/ruby/2.3.0/gems/capybara-2.13.0/lib/capybara/selenium/driver.rb:22:in `browser'
/opt/system/vendor/bundle/ruby/2.3.0/gems/capybara-2.13.0/lib/capybara/selenium/driver.rb:55:in `visit'
/opt/system/vendor/bundle/ruby/2.3.0/gems/capybara-2.13.0/lib/capybara/session.rb:254:in `visit'
/opt/system/vendor/bundle/ruby/2.3.0/gems/capybara-2.13.0/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
/opt/system/features/step_definitions/web_steps.rb:24:in `block in <top (required)>'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-2.99.0/lib/cucumber/core_ext/instance_exec.rb:25:in `instance_exec'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-2.99.0/lib/cucumber/core_ext/instance_exec.rb:25:in `block in cucumber_instance_exec'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-2.99.0/lib/cucumber/core_ext/instance_exec.rb:42:in `cucumber_run_with_backtrace_filtering'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-2.99.0/lib/cucumber/core_ext/instance_exec.rb:13:in `cucumber_instance_exec'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-2.99.0/lib/cucumber/rb_support/rb_step_definition.rb:102:in `invoke'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-2.99.0/lib/cucumber/step_match.rb:27:in `invoke'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-2.99.0/lib/cucumber/step_match.rb:20:in `block in activate'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/action.rb:23:in `execute'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/step.rb:31:in `execute'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/runner.rb:104:in `execute'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/runner.rb:51:in `execute'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/runner.rb:26:in `test_step'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/step.rb:16:in `describe_to'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:26:in `block (3 levels) in describe_to'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:25:in `each'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:25:in `block (2 levels) in describe_to'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-2.99.0/lib/cucumber/filters/prepare_world.rb:22:in `block in test_case'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/around_hook.rb:16:in `execute'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/runner.rb:104:in `execute'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/runner.rb:51:in `execute'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/runner.rb:33:in `around_hook'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/around_hook.rb:11:in `describe_to'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:106:in `block (2 levels) in compose_around_hooks'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:107:in `compose_around_hooks'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:24:in `block in describe_to'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/runner.rb:18:in `test_case'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-2.99.0/lib/cucumber/filters/prepare_world.rb:11:in `test_case'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-2.99.0/lib/cucumber/filters/apply_around_hooks.rb:8:in `test_case'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-2.99.0/lib/cucumber/filters/apply_after_hooks.rb:5:in `test_case'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-2.99.0/lib/cucumber/filters/apply_before_hooks.rb:5:in `test_case'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-2.99.0/lib/cucumber/filters/apply_after_step_hooks.rb:8:in `test_case'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-2.99.0/lib/cucumber/filters/activate_steps.rb:11:in `test_case'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-2.99.0/lib/cucumber/filters/quit.rb:11:in `test_case'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/locations_filter.rb:17:in `block in done'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/locations_filter.rb:16:in `each'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/locations_filter.rb:16:in `done'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/filter.rb:61:in `done'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/compiler.rb:23:in `done'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/gherkin/parser.rb:35:in `done'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core.rb:29:in `parse'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core.rb:18:in `compile'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-2.99.0/lib/cucumber/runtime.rb:67:in `run!'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-2.99.0/lib/cucumber/cli/main.rb:32:in `execute!'
/opt/system/vendor/bundle/ruby/2.3.0/gems/cucumber-2.99.0/bin/cucumber:8:in `<top (required)>'
bin/cucumber:8:in `load'
bin/cucumber:8:in `<main>'
features/developer_portal/authentication_providers.feature:13:in `And I go to the login page'
```

This is not the only case, but we seem to have some tests in the codebase that do not consistently / reliably pass. (i.e. a re-run of the pipeline may see the same test passing / failing).

This [non-determinism, as Martin Fowler puts it, must be eradicated](https://martinfowler.com/articles/nonDeterminism.html) (warning, longish read). 

Our approach so far is to run the entire pipeline again which is both slow (we have to wait twice as long) and adds costs (we have to run builds twice). 

The article, shared above, suggests that we should start moving all such tests that exhibit this non-determinism into a separate suite, where they can be "quarantined" and don't affect all runs of "healthy" test suites, with a longer-term goal of starting to clean this up. 

I presume there have already been several discussions on this topic (probably many), so I was wondering if there is already some roadmap around addressing this issue?

**Comment by Martouta** [comment]
Another random bug:
https://github.com/3scale/porta/blob/eeb9f810d4b267a985fe3d90b0577e713ba7571a/test/unit/logic/provider_upgrade_test.rb#L65-L68

**Comment by Martouta** [comment]
Fixed, right @gsaslis ? So... can we close this issue?

**Comment by gsaslis** [comment]
Yup!! @mikz worked some magic for that when we were implementing the pipeline in circleci.

**Comment by mikz** [comment]
For the record, the fix was to properly set up database cleaning:

https://github.com/3scale/porta/pull/140/commits/0ea042168a9cac7873aadb1f1c3733f5f1aba0c4
https://github.com/3scale/porta/pull/140/commits/0c359dddbfb004a00f3be1cee8ff3ff79fdb2c48

**Comment by gsaslis** [comment]
@mikz thanks for demystifying the "magic"... but please don't tell the kids about santa just yet... ; )
