### ISSUE TITLE
Bug loading the Admin Dashboard: No route matches {:action=>"show", :controller=>"api/applications", :id=>"AnApplicationID", :service_id=>nil} missing required keys: [:service_id]

### ISSUE THREAD

**Issue by Martouta** [3scale/porta#68]
**What happened**:

The error is raised in:
https://github.com/3scale/porta/blob/ce9f48098298fa11d556a1e9a1c4cf51023fb304/app/views/provider/admin/dashboards/widgets/_service_top_traffic.html.slim#L11
A bit of the Stacktrace is:
```
from app/views/provider/admin/dashboards/widgets/_service_top_traffic.html.slim:11:in `block in _app_views_provider_admin_dashboards_widgets__service_top_traffic_html_slim__4553944636662614043_143926580'
    from app/presenters/dashboard/top_traffic_presenter.rb:16:in `each'
    from app/presenters/dashboard/top_traffic_presenter.rb:16:in `each'
    from app/views/provider/admin/dashboards/widgets/_service_top_traffic.html.slim:9:in `_app_views_provider_admin_dashboards_widgets__service_top_traffic_html_slim__4553944636662614043_143926580'
    [...]
    from gems/draper-2.1.0/lib/draper/helper_proxy.rb:16:in `method_missing'
    from app/presenters/dashboard_widget_presenter.rb:20:in `render'
    from app/views/provider/admin/dashboard/widget/show.js.erb:1:in `_app_views_provider_admin_dashboard_widget_show_js_erb__475393332699954344_132493280'
```

The problem is at that point `item` is an instance of `TopTrafficPresenter::Application` and its `application` does not have a service. Which is not a big issue because we have the param `service_id` anyway but from the widget (like `widget.params['service_id']`).
But testing this and replicating it is not that easy and I am struggling... 😞In https://github.com/3scale/porta/pull/66 
And I've found another possible issue while trying to test this. If I do this (which does not mean it is in any way a proper way to start testing the previous problem, but I was just checking around to see if I find out how to test it):
```ruby
setup do
  @provider = FactoryGirl.create(:provider_account)
  @service = @provider.default_service
  FactoryGirl.create_list(:cinstance, 2, service: @service)
  login! @provider
end

test 'it renders the applications show links' do
  get provider_admin_dashboard_service_top_traffic_path(@service)
end
```
And with `binding.pry` at the beginning of `app/views/provider/admin/dashboards/widgets/_service_top_traffic.html.slim`.
Widget contains:
```
=> #<DashboardWidgetPresenter:0x007fc4e9085290
 @chart=nil,
 @current=0,
 @data={:current_range=>Sat, 01 Sep 2018..Mon, 01 Oct 2018, :previous_range=>Thu, 02 Aug 2018...Sat, 01 Sep 2018},
 @has_history=nil,
 @items=
  #<Dashboard::TopTrafficPresenter:0x007fc4e6457150
   @_current_items=[],
   @cinstances=
    [#<Cinstance:0x007fc4d1976830
      id: 256,
      # ...
     #<Cinstance:0x007fc4d19766c8
      id: 259,
      # ...
```
From this code:
https://github.com/3scale/porta/blob/340cff144aea10d2cca9ccd58909b49d7cecbe6a/app/views/provider/admin/dashboards/widgets/_service_top_traffic.html.slim#L6-L11
`loaded?` is true, but `widget.items.present?` is false but `widget.items` exists, it is just is a `DashboardWidgetPresenter` in this case. And `widget.items.each` never is going to happen, and this would be accesible only by `widget.cinstances.each`. but these are real Cinstances and not the class I've mentioned before.

/kind bug

**Comment by josemigallas** [comment]
@Martouta could you please add some reproducing steps?

**Comment by Martouta** [comment]
@josemigallas That's the problem, being able to reproduce it... 😝 I know about this bug from bugsnag, but I couldn't reproduce it myself because I don't have a real Backend. I am trying to stub it and fake it 😂
