### ISSUE TITLE
[Oracle] ActiveRecord::StatementInvalid: OCIError: ORA-04098: trigger 'RAILS.INVOICES_TENANT_ID' is invalid

### ISSUE THREAD

**Issue by Martouta** [3scale/porta#82]
### What happened

I see that error message in many tests. For example in the following test.

#### Error Message
```
ActiveRecord::StatementInvalid: OCIError: ORA-04098: trigger 'RAILS.INVOICES_TENANT_ID' is invalid and failed re-validation: INSERT INTO "INVOICES" ("PERIOD", "BUYER_ACCOUNT_ID", "PROVIDER_ACCOUNT_ID", "CREATED_AT", "UPDATED_AT", "ID") VALUES (:a1, :a2, :a3, :a4, :a5, :a6)...
```
#### Stacktrace
```
Failure:
test_#create_with_attributes_saved_correctly(Minitest::Result) [/opt/system/test/integration/finance/api/invoices_controller_test.rb:109]:
ActiveRecord::StatementInvalid: OCIError: ORA-04098: trigger 'RAILS.INVOICES_TENANT_ID' is invalid and failed re-validation: INSERT INTO "INVOICES" ("PERIOD", "BUYER_ACCOUNT_ID", "PROVIDER_ACCOUNT_ID", "CREATED_AT", "UPDATED_AT", "ID") VALUES (:a1, :a2, :a3, :a4, :a5, :a6)
    app/models/finance/billing_strategy.rb:164:in `block in create_invoice'
    app/models/finance/billing_strategy.rb:164:in `create_invoice'
    app/controllers/finance/api/invoices_controller.rb:158:in `create'
    lib/api_authentication/by_access_token.rb:159:in `enforce'
    lib/api_authentication/by_access_token.rb:109:in `enforce_access_token_permission'
    app/controllers/admin/api/base_controller.rb:40:in `block in notification_center'
    lib/notification_center.rb:30:in `silent_about'
    app/controllers/application_controller.rb:179:in `silent_about'
    app/controllers/admin/api/base_controller.rb:39:in `notification_center'
    lib/three_scale/middleware/multitenant.rb:116:in `_call'
    lib/three_scale/middleware/multitenant.rb:111:in `call'
    test/integration/finance/api/invoices_controller_test.rb:110:in `block (2 levels) in <class:InvoicesControllerTest>'
    test/integration/finance/api/invoices_controller_test.rb:109:in `block in <class:InvoicesControllerTest>'
```

### What you expected to happen

I would expect the test to pass 😝 

### How to reproduce it

No idea. I've seen it in Jenkins.

/kind bug

**Comment by hallelujah** [comment]
Yes it is solved here https://github.com/3scale/porta/pull/81/commits/50d52990ab1ff213170099b9c5c693a9178ec537

**Comment by Martouta** [comment]
Thanks 😍
